// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject1
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// openEnterNum - Use 'openEnterNumParams' to pass parameters into this method.
        /// </summary>
        public void openEnterNum()
        {
            #region Variable Declarations
            WinEdit uIContentEdit = this.UISpreadsheetWindow.UIContentWindow.UIContentEdit;
            WinWindow uIMenuStrip1Window = this.UISpreadsheetWindow.UIMenuStrip1Window;
            #endregion

            // Launch '%USERPROFILE%\Source\Repos\u0805396\Spreadsheet\SpreadsheetGUI\bin\Release\SpreadsheetGUI.exe'
            ApplicationUnderTest uISpreadsheetWindow = ApplicationUnderTest.Launch(this.openEnterNumParams.UISpreadsheetWindowExePath, this.openEnterNumParams.UISpreadsheetWindowAlternateExePath);

            // Type '33' in 'content' text box
            uIContentEdit.Text = this.openEnterNumParams.UIContentEditText;

            // Click 'menuStrip1' window
            Mouse.Click(uIMenuStrip1Window, new Point(401, 125));
        }
        
        /// <summary>
        /// RecordedMethod1 - Use 'RecordedMethod1Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WinList uIItemList = this.UIItemWindow.UIFolderViewWindow.UIItemList;
            WinEdit uIContentEdit = this.UISpreadsheetWindow.UIContentWindow.UIContentEdit;
            WinWindow uIMenuStrip1Window = this.UISpreadsheetWindow.UIMenuStrip1Window;
            #endregion

            // Click list box
            Mouse.Click(uIItemList, new Point(529, 40));

            // Launch '%USERPROFILE%\Source\Repos\u0805396\Spreadsheet\SpreadsheetGUI\bin\Release\SpreadsheetGUI.exe'
            ApplicationUnderTest uISpreadsheetWindow = ApplicationUnderTest.Launch(this.RecordedMethod1Params.UISpreadsheetWindowExePath, this.RecordedMethod1Params.UISpreadsheetWindowAlternateExePath);

            // Type '7' in 'content' text box
            uIContentEdit.Text = this.RecordedMethod1Params.UIContentEditText;

            // Click 'menuStrip1' window
            Mouse.Click(uIMenuStrip1Window, new Point(353, 132));

            // Click list box
            Mouse.Click(uIItemList, new Point(192, 334));
        }
        
        /// <summary>
        /// RecordedMethod2 - Use 'RecordedMethod2Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod2()
        {
            #region Variable Declarations
            WinEdit uIContentEdit = this.UISpreadsheetWindow.UIContentWindow.UIContentEdit;
            WinList uIItemList = this.UIItemWindow.UIFolderViewWindow.UIItemList;
            #endregion

            // Launch '%USERPROFILE%\Source\Repos\u0805396\Spreadsheet\SpreadsheetGUI\bin\Release\SpreadsheetGUI.exe'
            ApplicationUnderTest uISpreadsheetWindow = ApplicationUnderTest.Launch(this.RecordedMethod2Params.UISpreadsheetWindowExePath, this.RecordedMethod2Params.UISpreadsheetWindowAlternateExePath);

            // Type '6' in 'content' text box
            uIContentEdit.Text = this.RecordedMethod2Params.UIContentEditText;

            // Click list box
            Mouse.Click(uIItemList, new Point(538, 282));
        }
        
        #region Properties
        public virtual openEnterNumParams openEnterNumParams
        {
            get
            {
                if ((this.mopenEnterNumParams == null))
                {
                    this.mopenEnterNumParams = new openEnterNumParams();
                }
                return this.mopenEnterNumParams;
            }
        }
        
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public virtual RecordedMethod2Params RecordedMethod2Params
        {
            get
            {
                if ((this.mRecordedMethod2Params == null))
                {
                    this.mRecordedMethod2Params = new RecordedMethod2Params();
                }
                return this.mRecordedMethod2Params;
            }
        }
        
        public UISpreadsheetWindow UISpreadsheetWindow
        {
            get
            {
                if ((this.mUISpreadsheetWindow == null))
                {
                    this.mUISpreadsheetWindow = new UISpreadsheetWindow();
                }
                return this.mUISpreadsheetWindow;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow();
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private openEnterNumParams mopenEnterNumParams;
        
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private RecordedMethod2Params mRecordedMethod2Params;
        
        private UISpreadsheetWindow mUISpreadsheetWindow;
        
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'openEnterNum'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class openEnterNumParams
    {
        
        #region Fields
        /// <summary>
        /// Launch '%USERPROFILE%\Source\Repos\u0805396\Spreadsheet\SpreadsheetGUI\bin\Release\SpreadsheetGUI.exe'
        /// </summary>
        public string UISpreadsheetWindowExePath = "C:\\Users\\Matt\\Source\\Repos\\u0805396\\Spreadsheet\\SpreadsheetGUI\\bin\\Release\\Spread" +
            "sheetGUI.exe";
        
        /// <summary>
        /// Launch '%USERPROFILE%\Source\Repos\u0805396\Spreadsheet\SpreadsheetGUI\bin\Release\SpreadsheetGUI.exe'
        /// </summary>
        public string UISpreadsheetWindowAlternateExePath = "%USERPROFILE%\\Source\\Repos\\u0805396\\Spreadsheet\\SpreadsheetGUI\\bin\\Release\\Spread" +
            "sheetGUI.exe";
        
        /// <summary>
        /// Type '33' in 'content' text box
        /// </summary>
        public string UIContentEditText = "33";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Launch '%USERPROFILE%\Source\Repos\u0805396\Spreadsheet\SpreadsheetGUI\bin\Release\SpreadsheetGUI.exe'
        /// </summary>
        public string UISpreadsheetWindowExePath = "C:\\Users\\Matt\\Source\\Repos\\u0805396\\Spreadsheet\\SpreadsheetGUI\\bin\\Release\\Spread" +
            "sheetGUI.exe";
        
        /// <summary>
        /// Launch '%USERPROFILE%\Source\Repos\u0805396\Spreadsheet\SpreadsheetGUI\bin\Release\SpreadsheetGUI.exe'
        /// </summary>
        public string UISpreadsheetWindowAlternateExePath = "%USERPROFILE%\\Source\\Repos\\u0805396\\Spreadsheet\\SpreadsheetGUI\\bin\\Release\\Spread" +
            "sheetGUI.exe";
        
        /// <summary>
        /// Type '7' in 'content' text box
        /// </summary>
        public string UIContentEditText = "7";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod2'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class RecordedMethod2Params
    {
        
        #region Fields
        /// <summary>
        /// Launch '%USERPROFILE%\Source\Repos\u0805396\Spreadsheet\SpreadsheetGUI\bin\Release\SpreadsheetGUI.exe'
        /// </summary>
        public string UISpreadsheetWindowExePath = "C:\\Users\\Matt\\Source\\Repos\\u0805396\\Spreadsheet\\SpreadsheetGUI\\bin\\Release\\Spread" +
            "sheetGUI.exe";
        
        /// <summary>
        /// Launch '%USERPROFILE%\Source\Repos\u0805396\Spreadsheet\SpreadsheetGUI\bin\Release\SpreadsheetGUI.exe'
        /// </summary>
        public string UISpreadsheetWindowAlternateExePath = "%USERPROFILE%\\Source\\Repos\\u0805396\\Spreadsheet\\SpreadsheetGUI\\bin\\Release\\Spread" +
            "sheetGUI.exe";
        
        /// <summary>
        /// Type '6' in 'content' text box
        /// </summary>
        public string UIContentEditText = "6";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UISpreadsheetWindow : WinWindow
    {
        
        public UISpreadsheetWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Spreadsheet";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Spreadsheet");
            #endregion
        }
        
        #region Properties
        public UIContentWindow UIContentWindow
        {
            get
            {
                if ((this.mUIContentWindow == null))
                {
                    this.mUIContentWindow = new UIContentWindow(this);
                }
                return this.mUIContentWindow;
            }
        }
        
        public WinWindow UIMenuStrip1Window
        {
            get
            {
                if ((this.mUIMenuStrip1Window == null))
                {
                    this.mUIMenuStrip1Window = new WinWindow(this);
                    #region Search Criteria
                    this.mUIMenuStrip1Window.SearchProperties[WinWindow.PropertyNames.Name] = "menuStrip1";
                    this.mUIMenuStrip1Window.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
                    this.mUIMenuStrip1Window.WindowTitles.Add("Spreadsheet");
                    #endregion
                }
                return this.mUIMenuStrip1Window;
            }
        }
        
        public WinWindow UICellValueWindow
        {
            get
            {
                if ((this.mUICellValueWindow == null))
                {
                    this.mUICellValueWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUICellValueWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUICellValueWindow.WindowTitles.Add("Spreadsheet");
                    #endregion
                }
                return this.mUICellValueWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIContentWindow mUIContentWindow;
        
        private WinWindow mUIMenuStrip1Window;
        
        private WinWindow mUICellValueWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIContentWindow : WinWindow
    {
        
        public UIContentWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "content";
            this.WindowTitles.Add("Spreadsheet");
            #endregion
        }
        
        #region Properties
        public WinEdit UIContentEdit
        {
            get
            {
                if ((this.mUIContentEdit == null))
                {
                    this.mUIContentEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIContentEdit.WindowTitles.Add("Spreadsheet");
                    #endregion
                }
                return this.mUIContentEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIContentEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Desktop";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32769";
            #endregion
        }
        
        #region Properties
        public UIFolderViewWindow UIFolderViewWindow
        {
            get
            {
                if ((this.mUIFolderViewWindow == null))
                {
                    this.mUIFolderViewWindow = new UIFolderViewWindow(this);
                }
                return this.mUIFolderViewWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIFolderViewWindow mUIFolderViewWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIFolderViewWindow : WinWindow
    {
        
        public UIFolderViewWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1";
            #endregion
        }
        
        #region Properties
        public WinList UIItemList
        {
            get
            {
                if ((this.mUIItemList == null))
                {
                    this.mUIItemList = new WinList(this);
                }
                return this.mUIItemList;
            }
        }
        #endregion
        
        #region Fields
        private WinList mUIItemList;
        #endregion
    }
}
